id: vcf2circos
name: vcf2circos Application
description: vcf2circos Application.<br>This application generat a Circos plot from a VCF file.
category: VCF
version: 1.0.0
author: Antony Le Bechec
submitButton: Circos Plot
workflow:
  steps:
    - name: Circos plot 
      cmd: /bin/bash application.sh "$vcf" "$plot"
      bash: true
      stdout: true

  inputs:
    - id: vcf
      description: VCF file
      type: local_file
      accept: .vcf, .gz
      
  outputs:
    - id: plot
      description: Output Circos plot
      type: local_file
      mergeOutput: false
      download: true
      zip: false
      